-- SEQUENCE DROP
DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_AUTHORITY_CODE;
DROP SEQUENCE SEQ_MENU_CODE;
DROP SEQUENCE SEQ_LOGIN_LOG_NO;
DROP SEQUENCE SEQ_LOGIN_FAILED_NO;
DROP SEQUENCE SEQ_CHANGED_PWD_LOG_NO;

-- SEQUENCE CRAETE
CREATE SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_AUTHORITY_CODE;
CREATE SEQUENCE SEQ_MENU_CODE;
CREATE SEQUENCE SEQ_LOGIN_LOG_NO;
CREATE SEQUENCE SEQ_LOGIN_FAILED_NO;
CREATE SEQUENCE SEQ_CHANGED_PWD_LOG_NO;

-- TABLE DROP
DROP TABLE TBL_GLOBAL_MENU CASCADE CONSTRAINTS;
DROP TABLE TBL_AUTHENTICATED_MENU CASCADE CONSTRAINTS;
DROP TABLE TBL_MEMBER_ROLE CASCADE CONSTRAINTS;
DROP TABLE TBL_AUTHORITY CASCADE CONSTRAINTS;
DROP TABLE TBL_CHANGED_PWD_LOG CASCADE CONSTRAINTS;
DROP TABLE TBL_LOGIN_FAILED_LOG CASCADE CONSTRAINTS;
DROP TABLE TBL_LOGIN_LOG CASCADE CONSTRAINTS;
DROP TABLE TBL_MEMBER CASCADE CONSTRAINTS;


-- TABLE CREATE
CREATE TABLE TBL_AUTHENTICATED_MENU
(
    AUTHORITY_CODE    NUMBER NOT NULL,
    MENU_CODE    NUMBER NOT NULL
);


CREATE TABLE TBL_AUTHORITY
(
    AUTHORITY_CODE    NUMBER NOT NULL,
    AUTHORITY_NAME    VARCHAR2(255) NOT NULL,
    AUTHORITY_DESC    VARCHAR2(4000) NOT NULL
);


CREATE TABLE TBL_CHANGED_PWD_LOG
(
    CHANGED_PWD_LOG_NO    NUMBER NOT NULL,
    MEMBER_NO    NUMBER NOT NULL,
    BEFORE_CHANGED_PWD    CHAR(60) NOT NULL,
    CHANGED_PWD_DATE    CHAR(8) NOT NULL
);


CREATE TABLE TBL_GLOBAL_MENU
(
    MENU_CODE    NUMBER NOT NULL,
    MENU_NAME    VARCHAR2(255) NOT NULL,
    MENU_URL    VARCHAR2(255) NOT NULL,
    MENU_DESC    VARCHAR2(4000) NOT NULL,
    MENU_ORDER    NUMBER NOT NULL,
    REMOVED_YN    CHAR(1) DEFAULT 'N' NOT NULL,
    MENU_TYPE    NUMBER NOT NULL,
    REF_MENU_CODE    NUMBER
);


CREATE TABLE TBL_LOGIN_FAILED_LOG
(
    LOGIN_FAILED_LOG_NO    NUMBER NOT NULL,
    MEMBER_NO    NUMBER NOT NULL,
    LOGIN_FAILED_DATETIME    TIMESTAMP NOT NULL,
    LOGIN_TRIED_IP    CHAR(15) NOT NULL,
    LOGIN_FAILED_REASON    VARCHAR2(255) NOT NULL
);


CREATE TABLE TBL_LOGIN_LOG
(
    LOGIN_LOG_NO    NUMBER NOT NULL,
    MEMBER_NO    NUMBER NOT NULL,
    LOGIN_DATETIME    TIMESTAMP NOT NULL,
    LOGIN_IP    CHAR(15) NOT NULL,
    REFERER_URL    VARCHAR2(255) NOT NULL
);


CREATE TABLE TBL_MEMBER
(
    MEMBER_NO    NUMBER NOT NULL,
    MEMBER_ID    VARCHAR2(20) NOT NULL,
    MEMBER_PWD    CHAR(60) NOT NULL,
    TEMP_PWD_YN    CHAR(1) DEFAULT 'N' NOT NULL,
    PWD_CHANGED_DATETIME    DATE DEFAULT SYSDATE NOT NULL,
    PWD_EXP_DATE    CHAR(8) NOT NULL,
    MEMBER_NAME    VARCHAR2(20) NOT NULL,
    MEMBER_REGIST_DATETIME    DATE DEFAULT SYSDATE NOT NULL,
    ACCUM_LOGIN_COUNT    NUMBER DEFAULT 0 NOT NULL,
    LOGIN_FAILED_COUNT    NUMBER DEFAULT 0 NOT NULL,
    ACC_LOCK_YN    CHAR(1) DEFAULT 'N' NOT NULL,
    ACC_INACTIVE_YN    CHAR(1) DEFAULT 'N' NOT NULL,
    ACC_EXP_DATE    CHAR(8) NOT NULL,
    ACC_EXP_YN    CHAR(1) DEFAULT 'N' NOT NULL,
    ACC_SECESSION_DATETIME    DATE,
    ACC_SECESSION_YN    CHAR(1) DEFAULT 'N' NOT NULL
);


CREATE TABLE TBL_MEMBER_ROLE
(
    MEMBER_NO    NUMBER NOT NULL,
    AUTHORITY_CODE    NUMBER NOT NULL
);

CREATE UNIQUE INDEX IND_TBL_AUTHENTICATED_MENU ON TBL_AUTHENTICATED_MENU
( AUTHORITY_CODE,MENU_CODE );

CREATE UNIQUE INDEX IND_TBL_AUTHORITY ON TBL_AUTHORITY
( AUTHORITY_CODE );

CREATE UNIQUE INDEX IND_TBL_CHANGED_PWD_LOG ON TBL_CHANGED_PWD_LOG
( CHANGED_PWD_LOG_NO );

CREATE UNIQUE INDEX IND_TBL_GLOBAL_MENU ON TBL_GLOBAL_MENU
( MENU_CODE );

CREATE UNIQUE INDEX IND_TBL_LOGIN_FAILED_LOG ON TBL_LOGIN_FAILED_LOG
( LOGIN_FAILED_LOG_NO );


CREATE UNIQUE INDEX IND_TBL_LOGIN_LOG ON TBL_LOGIN_LOG
( LOGIN_LOG_NO );


CREATE UNIQUE INDEX IND_TBL_MEMBER ON TBL_MEMBER
( MEMBER_NO );


CREATE UNIQUE INDEX IND_TBL_MEMBER_ROLE ON TBL_MEMBER_ROLE
( MEMBER_NO,AUTHORITY_CODE);

INSERT
  INTO TBL_MEMBER
(
  MEMBER_NO
, MEMBER_ID
, MEMBER_PWD
, TEMP_PWD_YN
, PWD_CHANGED_DATETIME
, PWD_EXP_DATE
, MEMBER_NAME
, MEMBER_REGIST_DATETIME
, ACCUM_LOGIN_COUNT
, LOGIN_FAILED_COUNT
, ACC_LOCK_YN
, ACC_INACTIVE_YN
, ACC_EXP_DATE
, ACC_EXP_YN
, ACC_SECESSION_DATETIME
, ACC_SECESSION_YN
) 
VALUES
(
  SEQ_MEMBER_NO.NEXTVAL
, 'admin'
, '$2a$10$X45Jsk42JefSGVcnYKccweDQ1dz2xRMFTfKMtnOlpB1ZQMMsnhQlK'
, 'N'
, TO_DATE('22/07/05', 'RR/MM/DD')
, TO_DATE('22/10/10', 'RR/MM/DD')
, '관리자'
, TO_DATE('22/07/04', 'RR/MM/DD')
, 0
, 0
, DEFAULT
, DEFAULT
, TO_DATE('23/07/05', 'RR/MM/DD')
, DEFAULT
, NULL
, DEFAULT
);

INSERT INTO TBL_MEMBER_ROLE VALUES(1, 1);
INSERT INTO TBL_MEMBER_ROLE VALUES(1, 2);

INSERT INTO TBL_AUTHORITY VALUES(SEQ_AUTHORITY_CODE.NEXTVAL, 'ROLE_ADMIN', '관리자');
INSERT INTO TBL_AUTHORITY VALUES(SEQ_AUTHORITY_CODE.NEXTVAL, 'ROLE_MEMBER', '일반회원');

COMMIT;