-- DDL
-- ALTER: 객체를 수정하는 구문
-- 테이블 객체 수정: ALTER TABLE 테이블명 수정할 내용;
-- 컬럼 추가/삭제/변경, 제약조건 추가/삭제/변경
-- 테이블명 변경, 제약조건 이름 변경
 
SELECT * FROM DEPT_COPY;

-- 컬럼 추가
ALTER TABLE DEPT_COPY
ADD (LNAME VARCHAR2(20));

-- 컬럼 삭제
ALTER TABLE DEPT_COPY
DROP COLUMN LNAME;

-- 컬럼 생성 시 DEFAULT값 지정
ALTER TABLE DEPT_COPY
ADD (CNAME VARCHAR2(20) DEFAULT '한국');

-- 컬럼에 제약조건 추가
CREATE TABLE DEPT_COPY2
AS
SELECT A.*
  FROM DEPARTMENT A;

SELECT
       A.TABLE_NAME
     , A.CONSTRAINT_NAME
     , A.SEARCH_CONDITION
     , A.CONSTRAINT_TYPE
     , B.COLUMN_NAME
  FROM USER_CONSTRAINTS A
  JOIN USER_CONS_COLUMNS B ON (A.CONSTRAINT_NAME = B.CONSTRAINT_NAME)
 WHERE A.TABLE_NAME = 'DEPT_COPY2';

ALTER TABLE DEPT_COPY2
ADD CONSTRAINT PK_DEPT_ID2 PRIMARY KEY(DEPT_ID);

ALTER TABLE DEPT_COPY2
ADD CONSTRAINT UK_DEPT_TITLE2 UNIQUE(DEPT_TITLE);

-- NOT NULL 같은 경우는 수정한다는 의미의 MODIFY를 통해서 NOT NULL 제약조건을 추가 및 삭제하는 개념을 할 수 있다.
ALTER TABLE DEPT_COPY2
MODIFY LOCATION_ID CONSTRAINT NN_LID NULL;     -- NOT NULL 제약조건 제거

ALTER TABLE DEPT_COPY2
MODIFY LOCATION_ID CONSTRAINT NN_LID NOT NULL; -- NOT NULL 제약조건 추가

-- 컬럼 자료형 수정
-- 단, 조심해야 할 것은 컬럼의 크기를 줄이는 경우에는
-- 변경하려는 자료형의 크기를 초과하는 데이터가 없을 때만 가능하다.
DESC DEPT_COPY2;

ALTER TABLE DEPT_COPY2
MODIFY DEPT_ID CHAR(3)
MODIFY DEPT_TITLE VARCHAR2(30)
MODIFY LOCATION_ID VARCHAR2(3);

ALTER TABLE DEPT_COPY
MODIFY CNAME DEFAULT '미국';

SELECT * FROM DEPT_COPY;

INSERT
  INTO DEPT_COPY
VALUES
(
  'D0'
, '생산부'
, 'L2'
, DEFAULT
);

SELECT * FROM DEPT_COPY;

-- 컬럼 삭제
SELECT * FROM DEPT_COPY2;

ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_TITLE;

ALTER TABLE DEPT_COPY2
DROP COLUMN LOCATION_ID;

-- 테이블은 최소 한 개의 컬럼이 남아 있어야 한다.
ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_ID;    -- 마지막 하나의 컬럼은 삭제 실패

CREATE TABLE TB1(
  PK NUMBER PRIMARY KEY NOT NULL,
  FK NUMBER REFERENCES TB1,
  COL1 NUMBER,
  CHECK(FK > 0 AND COL1 > 0)
);

-- 컬럼 삭제 시 다른 컬럼이 참조하고 있는 컬럼이 있다면 해당 부모 열을 삭제할 수 없다.
ALTER TABLE TB1
DROP COLUMN PK;

-- 강제로라도 부모 열을 지우고 싶다면 제약조건도 함께 삭제가 되어야 한다.(CASCADE CONSTRAINTS)
ALTER TABLE TB1
DROP COLUMN PK CASCADE CONSTRAINTS;

DESC TB1;

-- 제약조건 삭제
CREATE TABLE CONST_EMP(
  ENAME VARCHAR2(20) NOT NULL,
  ENO VARCHAR2(15) NOT NULL,
  MARRIAGE CHAR(1) DEFAULT 'N',
  EID CHAR(3),
  EMAIL VARCHAR2(30),
  JID CHAR(2),
  MID CHAR(3),
  DID CHAR(2),
  CONSTRAINT CK_MARRIAGE CHECK(MARRIAGE IN ('Y','N')),
  CONSTRAINT PK_EID PRIMARY KEY(EID),
  CONSTRAINT UK_ENO UNIQUE(ENO),
  CONSTRAINT UK_EMAIL UNIQUE(EMAIL),
  CONSTRAINT FK_JID FOREIGN KEY(JID)
  REFERENCES JOB(JOB_CODE) ON DELETE SET NULL,
  CONSTRAINT FK_MID FOREIGN KEY(MID)
  REFERENCES CONST_EMP ON DELETE SET NULL,
  CONSTRAINT FK_DID FOREIGN KEY(DID)
  REFERENCES DEPARTMENT ON DELETE CASCADE
);

-- 제약조건 1개 삭제 시
ALTER TABLE CONST_EMP
DROP CONSTRAINT CK_MARRIAGE;

SELECT
       A.TABLE_NAME
     , A.CONSTRAINT_NAME
     , A.SEARCH_CONDITION
     , A.CONSTRAINT_TYPE
     , B.COLUMN_NAME
  FROM USER_CONSTRAINTS A
  JOIN USER_CONS_COLUMNS B ON (A.CONSTRAINT_NAME = B.CONSTRAINT_NAME)
 WHERE A.TABLE_NAME = 'CONST_EMP';
 
-- 제약조건 여러 개 삭제 시
ALTER TABLE CONST_EMP
DROP CONSTRAINT FK_DID
DROP CONSTRAINT FK_JID
DROP CONSTRAINT FK_MID;

-- NOT NULL 제약조건 삭제 시 MODIFY 사용
ALTER TABLE CONST_EMP
MODIFY (ENAME NULL, ENO NULL);

-- 컬럼 이름 변경
CREATE TABLE DEPT_COPY3
AS
SELECT A.*
  FROM DEPARTMENT A;

DESC DEPT_COPY3;

ALTER TABLE DEPT_COPY3
RENAME COLUMN DEPT_ID TO DEPT_CODE;

-- 제약조건 이름 변경
ALTER TABLE DEPT_COPY3
ADD CONSTRAINT PK_DEPT_CODE3 PRIMARY KEY(DEPT_CODE);
 
ALTER TABLE DEPT_COPY3
RENAME CONSTRAINT PK_DEPT_CODE3 TO PK_DCODE;

-- 테이블 이름 변경
ALTER TABLE DEPT_COPY3
RENAME TO DEPT_TEST;
 
DESC DEPT_TEST;
 
-- 테이블 삭제
DROP TABLE DEPT_TEST CASCADE CONSTRAINTS; -- CASCADE CONSTRAINTS를 쓰면 부모 테이블이라도 삭제가 가능하다.
 
 


