-- 프로시저(PROCEDURE)
-- : PL/SQL문을 저장하는 객체이다.
--   필요할 때마다 복잡한 구문을 다시 입력 할 필요 없이
--   호출을 통해서 간단히 실행시키기 위한 목적으로 사용된다.
CREATE TABLE EMP_DUP
AS
SELECT A.*
  FROM EMPLOYEE A;
  
SELECT * FROM EMP_DUP;

-- 프로시저 생성
CREATE OR REPLACE PROCEDURE DEL_ALL_EMP
IS
BEGIN
  DELETE
    FROM EMP_DUP;
  COMMIT;
END;
/

-- 프로시저 실행
EXECUTE DEL_ALL_EMP;
SELECT * FROM EMP_DUP;

-- EXECUTE는 줄여서 쓸 수 있다.
EXEC DEL_ALL_EMP;

-- 프로시저를 관리하는 데이터 딕셔너리 뷰
SELECT
       A.*
  FROM USER_SOURCE A;

-- 매개변수 있는 프로시저
CREATE OR REPLACE PROCEDURE DEL_EMP_ID
(
  V_EMP_ID EMPLOYEE.EMP_ID%TYPE
)
IS
BEGIN
  DELETE
    FROM EMPLOYEE A
   WHERE A.EMP_ID = V_EMP_ID;
END;
/

EXEC DEL_EMP_ID('&사원번호');

SELECT * FROM EMPLOYEE WHERE EMP_ID = '201';
ROLLBACK;

-- IN/OUT 매개변수 있는 프로시저
CREATE OR REPLACE PROCEDURE SELECT_EMP_ID
(
  V_EMP_ID IN EMPLOYEE.EMP_ID%TYPE,
  V_EMP_NAME OUT EMPLOYEE.EMP_NAME%TYPE,
  V_SALARY OUT EMPLOYEE.SALARY%TYPE,
  V_BONUS OUT EMPLOYEE.BONUS%TYPE
)
IS
BEGIN
  SELECT A.EMP_NAME
       , A.SALARY
       , NVL(A.BONUS, 0)
    INTO V_EMP_NAME
       , V_SALARY
       , V_BONUS
    FROM EMPLOYEE A
   WHERE A.EMP_ID = V_EMP_ID;
END;
/

VARIABLE VAR_EMP_NAME VARCHAR2(30);
VARIABLE VAR_SALARY NUMBER;
VARIABLE VAR_BONUS NUMBER;

EXEC SELECT_EMP_ID('206', :VAR_EMP_NAME, :VAR_SALARY, :VAR_BONUS);

PRINT VAR_EMP_NAME;
PRINT VAR_SALARY;
PRINT VAR_BONUS;

-- 자동으로 PRINT 구문이 실행된다.
SET AUTOPRINT ON;








