-- 관리자 계정에서 OHGI 계정 추가
-- 계정 생성 및 권한 부여(SYSTEM 계정에서 할 것)
--CREATE USER C##OHGI IDENTIFIED BY OHGI;

-- 한 줄로 권한 두개 이상을 줄 수도 있다.
--GRANT CONNECT, RESOURCE TO C##OHGI;

-- 해당 계정에서 DDL 및 DML 작업을 하기 위해 필요한 작업(SYSTEM 계정에서 할 것)
--ALTER USER C##OHGI DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;  	  -- TABLESPACE 확보
--ALTER USER C##OHGI QUOTA 1024M ON SYSTEM;                           		  -- SYSTEM 공간 확보

-- TBL_CATEGORY(상품 카테고리)
DROP TABLE TBL_CATEGORY;
CREATE TABLE TBL_CATEGORY
(
    CATEGORY_CODE    NUMBER NOT NULL,
    CATEGORY_NAME    VARCHAR2(50) NOT NULL
);

ALTER TABLE TBL_CATEGORY
    ADD CONSTRAINT TBL_CATEGORY_PK PRIMARY KEY ( CATEGORY_CODE );

DROP SEQUENCE SEQ_CATEGORY_CODE;
CREATE SEQUENCE SEQ_CATEGORY_CODE
    START WITH 1
    NOCACHE;

COMMENT ON COLUMN TBL_CATEGORY.CATEGORY_CODE IS '카테고리코드';
COMMENT ON COLUMN TBL_CATEGORY.CATEGORY_NAME IS '카테고리명';

-- TBL_MEMBER(회원)
DROP TABLE TBL_MEMBER;
CREATE TABLE TBL_MEMBER
(
    MEMBER_CODE    NUMBER NOT NULL,
    MEMBER_ID        VARCHAR2(255) UNIQUE NOT NULL,
    MEMBER_NAME  VARCHAR2(255) NOT NULL,
    MEMBER_PASSWORD    VARCHAR2(255) NOT NULL,
    MEMBER_EMAIL    VARCHAR2(255)
);

ALTER TABLE TBL_MEMBER
    ADD CONSTRAINT TBL_MEMBER_PK PRIMARY KEY ( MEMBER_CODE );

DROP SEQUENCE SEQ_MEMBER_CODE;
CREATE SEQUENCE SEQ_MEMBER_CODE
    START WITH 1
    NOCACHE;

COMMENT ON COLUMN TBL_MEMBER.MEMBER_CODE IS '회원코드';
COMMENT ON COLUMN TBL_MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN TBL_MEMBER.MEMBER_NAME IS '회원이름';
COMMENT ON COLUMN TBL_MEMBER.MEMBER_PASSWORD IS '비밀번호';
COMMENT ON COLUMN TBL_MEMBER.MEMBER_EMAIL IS '이메일';

-- TBL_AUTHORITY(권한)
DROP TABLE TBL_AUTHORITY;
CREATE TABLE TBL_AUTHORITY
(
    AUTHORITY_CODE NUMBER NOT NULL,
    AUTHORITY_NAME VARCHAR2(255) NOT NULL,
    AUTHORITY_DESC VARCHAR2(4000) NOT NULL
);

ALTER TABLE TBL_AUTHORITY
    ADD CONSTRAINT TBL_AUTHORITY_PK PRIMARY KEY (AUTHORITY_CODE);

DROP SEQUENCE SEQ_AUTHORITY_CODE;
CREATE SEQUENCE SEQ_AUTHORITY_CODE
    START WITH 1
    NOCACHE;

COMMENT ON COLUMN TBL_AUTHORITY.AUTHORITY_CODE IS '권한코드';
COMMENT ON COLUMN TBL_AUTHORITY.AUTHORITY_NAME IS '권한명';
COMMENT ON COLUMN TBL_AUTHORITY.AUTHORITY_DESC IS '권한설명';

-- TBL_MEMBER_ROLE(회원별권한)
DROP TABLE TBL_MEMBER_ROLE;
CREATE TABLE TBL_MEMBER_ROLE
(
    MEMBER_CODE NUMBER NOT NULL,
    AUTHORITY_CODE NUMBER NOT NULL
);

ALTER TABLE TBL_MEMBER_ROLE
    ADD CONSTRAINT TBL_MEMBER_ROLE_PK PRIMARY KEY (MEMBER_CODE, AUTHORITY_CODE);

COMMENT ON COLUMN TBL_MEMBER_ROLE.MEMBER_CODE IS '회원코드';
COMMENT ON COLUMN TBL_MEMBER_ROLE.AUTHORITY_CODE IS '권한코드';

-- TBL_ORDER(주문)
DROP TABLE TBL_ORDER;
CREATE TABLE TBL_ORDER
(
    ORDER_CODE    NUMBER NOT NULL,
    PRODUCT_CODE    NUMBER NOT NULL,
    ORDER_MEMBER    NUMBER NOT NULL,
    ORDER_PHONE    VARCHAR2(255) NOT NULL,
    ORDER_EMAIL    VARCHAR2(255) NOT NULL,
    ORDER_RECEIVER    VARCHAR2(255) NOT NULL,
    ORDER_ADDRESS    VARCHAR2(500) NOT NULL,
    ORDER_AMOUNT    VARCHAR2(50) NOT NULL,
    ORDER_DATE    VARCHAR2(255) NOT NULL    
);

ALTER TABLE TBL_ORDER
    ADD CONSTRAINT TBL_ORDER_PK PRIMARY KEY ( ORDER_CODE );

DROP SEQUENCE SEQ_ORDER_CODE;
CREATE SEQUENCE SEQ_ORDER_CODE
    START WITH 1
    NOCACHE;

COMMENT ON COLUMN TBL_ORDER.ORDER_CODE IS '주문식별번호';
COMMENT ON COLUMN TBL_ORDER.PRODUCT_CODE IS '상품코드';
COMMENT ON COLUMN TBL_ORDER.ORDER_MEMBER IS '회원코드';
COMMENT ON COLUMN TBL_ORDER.ORDER_PHONE IS '핸드폰번호';
COMMENT ON COLUMN TBL_ORDER.ORDER_EMAIL IS '이메일주소';
COMMENT ON COLUMN TBL_ORDER.ORDER_RECEIVER IS '받는사람';
COMMENT ON COLUMN TBL_ORDER.ORDER_ADDRESS IS '배송주소';
COMMENT ON COLUMN TBL_ORDER.ORDER_AMOUNT IS '주문갯수';
COMMENT ON COLUMN TBL_ORDER.ORDER_DATE IS '주문일자';

-- TBL_PRODUCT(상품)
DROP TABLE TBL_PRODUCT;

CREATE TABLE TBL_PRODUCT
(
    PRODUCT_CODE    NUMBER NOT NULL,
    PRODUCT_NAME    VARCHAR2(255) NOT NULL,
    PRODUCT_PRICE    VARCHAR2(255) NOT NULL,
    PRODUCT_DESCRIPTION    VARCHAR2(1000),
    PRODUCT_ORDERABLE    VARCHAR2(5) NOT NULL,
    CATEGORY_CODE    NUMBER,
    PRODUCT_IMAGE_URL    VARCHAR2(255) NOT NULL,
    PRODUCT_STOCK    NUMBER NOT NULL
);

ALTER TABLE TBL_PRODUCT
    ADD CONSTRAINT TBL_PRODUCT_PK PRIMARY KEY ( PRODUCT_CODE );

DROP SEQUENCE SEQ_PRODUCT_CODE;
CREATE SEQUENCE SEQ_PRODUCT_CODE
    START WITH 1
    NOCACHE;

COMMENT ON COLUMN TBL_PRODUCT.PRODUCT_CODE IS '상품코드';
COMMENT ON COLUMN TBL_PRODUCT.PRODUCT_NAME IS '상품명';
COMMENT ON COLUMN TBL_PRODUCT.PRODUCT_PRICE IS '상품가격';
COMMENT ON COLUMN TBL_PRODUCT.PRODUCT_DESCRIPTION IS '상품설명';
COMMENT ON COLUMN TBL_PRODUCT.PRODUCT_ORDERABLE IS '구매가능여부';
COMMENT ON COLUMN TBL_PRODUCT.CATEGORY_CODE IS '카테고리코드';
COMMENT ON COLUMN TBL_PRODUCT.PRODUCT_IMAGE_URL IS '상품이미지경로';
COMMENT ON COLUMN TBL_PRODUCT.PRODUCT_STOCK IS '상품재고';

-- TBL_REVIEW(상품리뷰)
DROP TABLE TBL_REVIEW;
CREATE TABLE TBL_REVIEW
(
    REVIEW_CODE    NUMBER NOT NULL,
    PRODUCT_CODE    NUMBER NOT NULL,
    MEMBER_CODE    NUMBER NOT NULL,
    REVIEW_TITLE    VARCHAR2(255) NOT NULL,
    REVIEW_CONTENT    VARCHAR2(1000) NOT NULL,
    REVIEW_CREATE_DATE    VARCHAR2(255) NOT NULL
);

ALTER TABLE TBL_REVIEW
    ADD CONSTRAINT TBL_REVIEW_PK PRIMARY KEY ( REVIEW_CODE );

DROP SEQUENCE SEQ_REVIEW_CODE;
CREATE SEQUENCE SEQ_REVIEW_CODE
    START WITH 1
    NOCACHE;

COMMENT ON COLUMN TBL_REVIEW.REVIEW_CODE IS '리뷰식별번호';
COMMENT ON COLUMN TBL_REVIEW.PRODUCT_CODE IS '상품코드';
COMMENT ON COLUMN TBL_REVIEW.MEMBER_CODE IS '회원코드';
COMMENT ON COLUMN TBL_REVIEW.REVIEW_TITLE IS '리뷰제목';
COMMENT ON COLUMN TBL_REVIEW.REVIEW_CONTENT IS '리뷰내용';
COMMENT ON COLUMN TBL_REVIEW.REVIEW_CREATE_DATE IS '작성일';


